system: # OPTIONS
  username: ros2-dev
  simulation: true
robot:
  type: universal_robots # universal_robots / techman_robots
  model: ur10
  ip: 192.168.56.101
scene:
  pallet_left:
    size: "0.8 1.2 0.144"
    mesh: "/home/ws/.github/Company_data/RC10_meshes/Paleta_small.stl"
    position: "-0.79 -0.1 0.0"
    orientation: "0.0 0.0 0.0"
    parent: "world"
  pallet_right:
    # size: "0.8 1.2 0.144"
    mesh: "/home/ws/.github/Company_data/RC10_meshes/Paleta_small.stl"
    position: "0.79 -0.1 0.0"
    orientation: "0.0 0.0 0.0"
    parent: "world"
  station:
    size: "0.5 0.5 1.2"
    position: "0.0 0.0 0.0"
    orientation: "0.0 0.0 0.0"
    parent: "pallet_left"
  # extention: 0.49
  # extention: 0.49
  # extention: 0.49
  # retracted: 0.71
  # xyz: "0.0 -0.09 0.0"
  # rpy: "0.0 0.0 3.14"
# gripper:
  # xyz: "0.03 0.0 0.0"
  # rpy: "0.0 0.0 3.14"
# padding_j23:
  # xyz: "-0.6 0.0 0.2"
  # rpy: "0.0 0.0 1.57"
# padding_j34:
  # xyz: "-0.033 0.0 0.03"
  # rpy: "0.0 3.14 -1.57"
# padding_j5:
  # xyz: "0.0005 0.0 -0.02"
  # rpy: "1.57 0.0 3.14"
# pallet_right:
  # xyz: "0.79 -0.1 0.0"
  # rpy: "0.0 0.0 0.0"
# pallet_left:
  # xyz: "-0.79 -0.1 0.0"
  # rpy: "0.0 0.0 0.0"
# base:
  # xyz: "0.0 0.0 0.0"
  # rpy: "0.0 0.0 0.0"
# teaching_tool:
  # length: 0.0
  # xyz: "-0.03 0.0 0.15"
  # rpy: "0.0 0.0 0.0"
# gripper_pads:
  # distance: 0.0
  # xyz: "0.0 0.0 0.11"
  # rpy: "0.0 0.0 0.0"
# 
# 